#!/bin/bash

alias ll="ls -alh"
alias l="ls -a"

alias pacman="sudo pacman"

alias v=nvim
alias vim=nvim


reload_waybar() {
	pkill waybar && hyprctl dispatch exec waybar
}


alias deepseek="ollama run deepseek-r1"

